[deps]
Bijectors = "76274a88-744f-5084-9051-94815aaf08c4"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CategoricalArrays = "324d7699-5711-5eae-9e2f-1d82baa6b597"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
LazyArrays = "5078a376-72f3-5289-bfd5-ec5146d43c02"
PDMats = "90014a1f-27ba-587c-ab20-58faa44d9150"
ParetoSmooth = "a68b5a21-f429-434e-8bfa-46b447300aac"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
StatsFuns = "4c63d2b9-4356-54db-8cca-17b64c39e42c"
TransformVariables = "84d833dd-6860-57f9-a1a7-6da5db126cff"
Turing = "fce5fe82-541a-59a6-adf8-730c64b5f9a0"

[compat]
Bijectors = "0.13"
CSV = "0.10"
CategoricalArrays = "0.10"
DataFrames = "1"
LazyArrays = "2"
PDMats = "0.11"
ParetoSmooth = "0.7"
StatsBase = "0.34"
StatsFuns = "1"
TransformVariables = "0.8"
Turing = "0.32"
julia = "1"
